development:
  adapter: mysql
  database: haiku_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: haiku_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: haiku_production
  username: root
  password:
  host: localhost
