# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "haiku_tags", :force => true do |t|
  end

  create_table "haikus", :force => true do |t|
    t.column "title", :string
    t.column "line1", :string
    t.column "line2", :string
    t.column "line3", :string
  end

  create_table "haikus_tags", :id => false, :force => true do |t|
    t.column "haiku_id", :integer, :default => 0, :null => false
    t.column "tag_id",   :integer, :default => 0, :null => false
  end

  add_index "haikus_tags", ["haiku_id"], :name => "index_haikus_tags_on_haiku_id"
  add_index "haikus_tags", ["tag_id"], :name => "index_haikus_tags_on_tag_id"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

end
