development:
  adapter: mysql
  database: haiku_development
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: haiku_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: trunk_production
  username: root
  password:
  host: localhost