# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "haiku_comments", :force => true do |t|
    t.column "haiku_id",   :integer,                                  :null => false
    t.column "user_id",    :integer,                                  :null => false
    t.column "text",       :string,   :limit => 1000, :default => "", :null => false
    t.column "created_at", :datetime,                                 :null => false
  end

  add_index "haiku_comments", ["haiku_id", "created_at"], :name => "index_haiku_comments_on_haiku_id_and_created_at"
  add_index "haiku_comments", ["user_id", "created_at"], :name => "index_haiku_comments_on_user_id_and_created_at"

  create_table "haiku_favorites", :id => false, :force => true do |t|
    t.column "user_id",    :integer, :null => false
    t.column "haiku_id",   :integer, :null => false
    t.column "created_at", :integer, :null => false
  end

  add_index "haiku_favorites", ["user_id", "haiku_id"], :name => "index_haiku_favorites_on_user_id_and_haiku_id", :unique => true
  add_index "haiku_favorites", ["haiku_id", "user_id", "created_at"], :name => "index_haiku_favorites_on_haiku_id_and_user_id_and_created_at"
  add_index "haiku_favorites", ["created_at", "haiku_id"], :name => "index_haiku_favorites_on_created_at_and_haiku_id"

  create_table "haiku_tags", :id => false, :force => true do |t|
    t.column "haiku_id",   :integer,  :null => false
    t.column "tag_id",     :integer,  :null => false
    t.column "created_at", :datetime, :null => false
  end

  add_index "haiku_tags", ["tag_id", "haiku_id"], :name => "index_haiku_tags_on_tag_id_and_haiku_id", :unique => true
  add_index "haiku_tags", ["haiku_id", "tag_id"], :name => "index_haiku_tags_on_haiku_id_and_tag_id"
  add_index "haiku_tags", ["created_at", "tag_id"], :name => "index_haiku_tags_on_created_at_and_tag_id"

  create_table "haikus", :force => true do |t|
    t.column "line1",                 :string,   :default => "", :null => false
    t.column "line2",                 :string,   :default => "", :null => false
    t.column "line3",                 :string,   :default => "", :null => false
    t.column "user_id",               :integer,                  :null => false
    t.column "haiku_favorites_count", :integer,  :default => 0,  :null => false
    t.column "created_at",            :datetime,                 :null => false
  end

  add_index "haikus", ["user_id"], :name => "index_haikus_on_user_id"
  add_index "haikus", ["created_at"], :name => "index_haikus_on_created_at"

  create_table "school_haikus", :id => false, :force => true do |t|
    t.column "school_id",  :integer,  :null => false
    t.column "haiku_id",   :integer,  :null => false
    t.column "created_at", :datetime, :null => false
  end

  add_index "school_haikus", ["school_id", "haiku_id"], :name => "index_school_haikus_on_school_id_and_haiku_id", :unique => true
  add_index "school_haikus", ["haiku_id", "school_id"], :name => "index_school_haikus_on_haiku_id_and_school_id"

  create_table "school_users", :id => false, :force => true do |t|
    t.column "school_id", :integer,                 :null => false
    t.column "user_id",   :integer,                 :null => false
    t.column "user_type", :string,  :default => "", :null => false
  end

  add_index "school_users", ["school_id", "user_id"], :name => "index_school_users_on_school_id_and_user_id", :unique => true
  add_index "school_users", ["user_id", "school_id"], :name => "index_school_users_on_user_id_and_school_id"

  create_table "schools", :force => true do |t|
    t.column "name",        :string,   :limit => 100,  :default => "", :null => false
    t.column "description", :string,   :limit => 1000, :default => "", :null => false
    t.column "isadultonly", :boolean,                                  :null => false
    t.column "isprivate",   :boolean,                                  :null => false
    t.column "created_at",  :datetime,                                 :null => false
  end

  add_index "schools", ["name"], :name => "index_schools_on_name", :unique => true
  add_index "schools", ["created_at"], :name => "index_schools_on_created_at"

  create_table "tags", :force => true do |t|
    t.column "name",             :string,   :limit => 64, :default => "", :null => false
    t.column "haiku_tags_count", :integer,                :default => 0,  :null => false
    t.column "created_at",       :datetime,                               :null => false
  end

  add_index "tags", ["name"], :name => "index_tags_on_name", :unique => true
  add_index "tags", ["haiku_tags_count"], :name => "index_tags_on_haiku_tags_count"
  add_index "tags", ["created_at"], :name => "index_tags_on_created_at"

  create_table "user_logins", :id => false, :force => true do |t|
    t.column "user_id",   :integer,  :null => false
    t.column "logindate", :datetime, :null => false
  end

  add_index "user_logins", ["user_id"], :name => "user_logins_user_id_foreign_key"

  create_table "user_users", :id => false, :force => true do |t|
    t.column "sourceuser_id", :integer, :null => false
    t.column "targetuser_id", :integer, :null => false
    t.column "accepted",      :boolean, :null => false
  end

  add_index "user_users", ["sourceuser_id"], :name => "user_users_sourceuser_id_foreign_key"
  add_index "user_users", ["targetuser_id"], :name => "user_users_targetuser_id_foreign_key"

  create_table "users", :force => true do |t|
    t.column "username",        :string,   :limit => 100, :default => "", :null => false
    t.column "useralias",       :string,   :limit => 100
    t.column "email",           :string,   :limit => 100, :default => "", :null => false
    t.column "hashed_password", :string,                  :default => "", :null => false
    t.column "salt",            :string,                  :default => "", :null => false
    t.column "created_at",      :datetime,                                :null => false
  end

  add_index "users", ["username"], :name => "index_users_on_username", :unique => true

end
